### ISSUE TITLE
Bug Report: The command `Open the Community Plugins settings` opens the Community Plugins catalog

### ISSUE THREAD

**Issue by nhan000** [pjeby/hotkey-helper#12]
As in the title, the command `Open the Community Plugins settings` opens the Community Plugins catalog, so it does the same thing as `Browse or search the Community Plugins catalog`.

I've tested this in the Sandbox Vault, latest Obsidian version (1.3.5), Windows 11.

**Comment by pjeby** [comment]
Hm.  That's bizarre.  I use that command all the time and that doesn't happen -- but I have it assigned to a hotkey, so it must be something to do with the open modal.  In fact, it works fine if you click the item in the command palette...

Wow, okay, what's happening is that if the plugin settings open while the enter key is still down, it going up is what triggers opening the plugin browser.  I've changed it in 0.3.18 to check for the key being pressed down instead of coming back up.

**Comment by nhan000** [comment]
hmm I have updated the plugin to 0.3.18 but it still opens the Community Plugins catalog when I press Enter in the command pallete. But you're right, it works fine when clicking it instead.

**Comment by pjeby** [comment]
Have you opened any other settings tabs since the update, or restarted Obsidian?  I can think of a way where the bug could stay active if you hadn't done either since the update.

**Comment by nhan000** [comment]
I have restarted Obsidian after the update but the bug is still there. What I can observe is the command `Open the Community Plugins settings` flash up the Community Plugins settings before opening the Plugins catalog, while the `Browse or search the Community Plugins catalog` open the Plugins catalog directly.

Anyway, it's not a severe bug. Plus, I can just press `esc` (on Windows) to go back to the Community Plugin settings. You can take your time to debug this (and I don't even know if you were able to reproduce it).

**Comment by pjeby** [comment]
Ok, it appears the upload was broken, and neither Github nor Obsidian were giving any visible errors about it.  The plugin was working fine on my machine but the upload on github was incomplete, and your Obsidian instance didn't complain about it in a visible way I guess.

I've updated the release, but you will probably have to uninstall and reinstall to get Obsidian to install it, since it thinks it already has it.

**Comment by nhan000** [comment]
It works great after reinstalling. Thanks so much!
